/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Admin: typeof import('./src/components/Admin.vue')['default']
    CommissionTiers: typeof import('./src/components/CommissionTiers.vue')['default']
    ContinentSelect: typeof import('./src/components/Controls/ContinentSelect.vue')['default']
    CountrySelect: typeof import('./src/components/Controls/CountrySelect.vue')['default']
    DynamicComponent: typeof import('./src/components/DynamicComponent.vue')['default']
    DynamicControl: typeof import('./src/components/DynamicControl.vue')['default']
    FormRow: typeof import('./src/components/Controls/FormRow.vue')['default']
    GMap: typeof import('./src/components/GMap.vue')['default']
    ImageUpload: typeof import('./src/components/Controls/ImageUpload.vue')['default']
    NavigationLinks: typeof import('./src/components/VendorTable/NavigationLinks.vue')['default']
    OpeningHours: typeof import('./src/components/OpeningHours.vue')['default']
    Pagination: typeof import('./src/components/VendorTable/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShippingAddress: typeof import('./src/components/ShippingAddress.vue')['default']
    ShippingFlat: typeof import('./src/components/ShippingFlat.vue')['default']
    ShippingTableRates: typeof import('./src/components/ShippingTableRates.vue')['default']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
    StateSelect: typeof import('./src/components/Controls/StateSelect.vue')['default']
    VendorEdit: typeof import('./src/components/VendorEdit.vue')['default']
    VendorTable: typeof import('./src/components/VendorTable.vue')['default']
    VendorTableCell: typeof import('./src/components/VendorTable/VendorTableCell.vue')['default']
  }
}
