<?php
/*
 * Filters for block patterns.
 */

/**
 * @param $content
 *
 * @return false|string
 */
function directory_theme_pattern_footer_default( $content ) {
	ob_start();
	?>
	<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg":"custom-color","bg_color":"#1f1b2d","mb_lg":"0","pb_lg":"0","position":"position-relative","anchor":"footer","className":"block-1618467995"} -->
	[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='custom-color'  bg_color='#1f1b2d'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='0'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg='0'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor='footer'  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-0 pb-0 bg-custom-color container-fluid position-relative" style="background-color:#1f1b2d" id="footer"><!-- wp:blockstrap/blockstrap-widget-container {"mb_lg":"","pt_lg":"1"} -->
		[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='1'  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-1 container"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","mb_lg":"","pt_lg":"6","className":"block-1618467995"} -->
			[bs_container container='row'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='6'  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-6 row"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","mb_lg":"0","position":"position-relative","display":"d-block","display_md":"d-md-flex","display_lg":"d-lg-flex","flex_justify_content_lg":"justify-content-lg-between","className":"block-1618467995"} -->
				[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='0'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display='d-block'  display_md='d-md-flex'  display_lg='d-lg-flex'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg='justify-content-lg-between'  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-0 d-block d-md-flex d-lg-flex col position-relative justify-content-between"><!-- wp:blockstrap/blockstrap-widget-container {"container":"","bg_on_text":true,"text_color":"white","className":"block-1618467995"} -->
					[bs_container container=''  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='true'  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 text-white"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"\u003cmark style=\u0022background-color:rgba(0, 0, 0, 0)\u0022 class=\u0022has-inline-color has-primary-color px-0\u0022\u003e\u003cstrong\u003eD\u003c/strong\u003e\u003c/mark\u003eirectory","html_tag":"div","font_size":"h4","mb_lg":"4","pb_lg":"3"} -->
						<div class="wp-block-blockstrap-blockstrap-widget-heading mb-4 pb-3 h4"><mark style="background-color:rgba(0, 0, 0, 0)" class="has-inline-color has-primary-color px-0"><strong>D</strong></mark>irectory</div>
						<!-- /wp:blockstrap/blockstrap-widget-heading -->

						<!-- wp:blockstrap/blockstrap-widget-nav {"inside_navbar":"0","container":"nav-light","flex_direction":"flex-column","font_size":"fs-sm","ml_lg":"","pl_lg":"0"} -->
						[bs_nav anchor=''  inside_navbar='0'  container='nav-light'  flex_direction='flex-column'  nav_style=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  nav_fill=''  font_size='fs-sm'  font_size_custom=''  bg=''  mt=''  mr='auto'  mb=''  ml='auto'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg='0'  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  width=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-nav" id="navbarNav_"><ul class="wp-block-blockstrap-blockstrap-widget-nav nav me-auto ms-auto me-lg-0 ps-0 nav-light flex-column fs-sm"><!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"info@ayecode.io","icon_class":"far fa-envelope","link_bg":"white","link_pt_lg":"0","link_pr_lg":"0","link_pb_lg":"0","link_pl_lg":"0","font_weight":"font-weight-normal","mt_lg":"0","mb_lg":"2","pt_lg":"0","pb_lg":"0","content":""} -->
								[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text='info@ayecode.io'  icon_class='far fa-envelope'  icon_aria_label=''  link_type=''  link_size=''  link_bg='white'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg='0'  link_pr_lg='0'  link_pb_lg='0'  link_pl_lg='0'  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg='0'  mr_lg=''  mb_lg='2'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='0'  pr_lg=''  pb_lg='0'  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
								<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

								<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"+44 1010101010","icon_class":"fas fa-mobile-alt","link_bg":"white","link_pt_lg":"0","link_pr_lg":"0","link_pb_lg":"0","link_pl_lg":"0","font_weight":"font-weight-normal","mb_lg":"2","content":""} -->
								[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text='+44 1010101010'  icon_class='fas fa-mobile-alt'  icon_aria_label=''  link_type=''  link_size=''  link_bg='white'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg='0'  link_pr_lg='0'  link_pb_lg='0'  link_pl_lg='0'  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='2'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
								<!-- /wp:blockstrap/blockstrap-widget-nav-item --></ul></div>[/bs_nav]
						<!-- /wp:blockstrap/blockstrap-widget-nav --></div>[/bs_container]
					<!-- /wp:blockstrap/blockstrap-widget-container -->

					<!-- wp:blockstrap/blockstrap-widget-container {"container":"","text_color":"white","content":"","className":"block-1618467995"} -->
					[bs_container container=''  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 text-white"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"Quick Links","html_tag":"h4","text_color":"light","font_size":"fs-base","mb_lg":""} -->
						<h4 class="wp-block-blockstrap-blockstrap-widget-heading text-light fs-base">Quick Links</h4>
						<!-- /wp:blockstrap/blockstrap-widget-heading -->

						<!-- wp:blockstrap/blockstrap-widget-nav {"inside_navbar":"0","container":"nav-light","flex_direction":"flex-column","font_size":"fs-sm","mr_lg":"","ml_lg":"","pl_lg":"0"} -->
						[bs_nav anchor=''  inside_navbar='0'  container='nav-light'  flex_direction='flex-column'  nav_style=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  nav_fill=''  font_size='fs-sm'  font_size_custom=''  bg=''  mt=''  mr='auto'  mb=''  ml='auto'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  width=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-nav" id="navbarNav_"><ul class="wp-block-blockstrap-blockstrap-widget-nav nav me-auto ms-auto ps-0 nav-light flex-column fs-sm"><!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"Accommodation","link_bg":"gray","link_pt_lg":"0","link_pr_lg":"0","link_pb_lg":"0","link_pl_lg":"0","font_weight":"font-weight-normal","mb_lg":"2","ml_lg":"0","pl_lg":"0","content":""} -->
								[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text='Accommodation'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg='gray'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg='0'  link_pr_lg='0'  link_pb_lg='0'  link_pl_lg='0'  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='2'  ml_lg='0'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
								<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

								<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"Food \u0026 Drink","link_bg":"gray","link_pt_lg":"0","link_pr_lg":"0","link_pb_lg":"0","link_pl_lg":"0","font_weight":"font-weight-normal","mb_lg":"2","ml_lg":"0","pl_lg":"0","content":""} -->
								[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text='Food &amp; Drink'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg='gray'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg='0'  link_pr_lg='0'  link_pb_lg='0'  link_pl_lg='0'  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='2'  ml_lg='0'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
								<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

								<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"Shopping","link_bg":"gray","link_pt_lg":"0","link_pr_lg":"0","link_pb_lg":"0","link_pl_lg":"0","font_weight":"font-weight-normal","mb_lg":"2","ml_lg":"0","pl_lg":"0","content":""} -->
								[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text='Shopping'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg='gray'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg='0'  link_pr_lg='0'  link_pb_lg='0'  link_pl_lg='0'  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='2'  ml_lg='0'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
								<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

								<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"Art \u0026 History","link_bg":"gray","link_pt_lg":"0","link_pr_lg":"0","link_pb_lg":"0","link_pl_lg":"0","font_weight":"font-weight-normal","mb_lg":"2","ml_lg":"0","pl_lg":"0","content":""} -->
								[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text='Art &amp; History'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg='gray'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg='0'  link_pr_lg='0'  link_pb_lg='0'  link_pl_lg='0'  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='2'  ml_lg='0'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
								<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

								<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"Entertainment","link_bg":"gray","link_pt_lg":"0","link_pr_lg":"0","link_pb_lg":"0","link_pl_lg":"0","font_weight":"font-weight-normal","mb_lg":"2","ml_lg":"0","pl_lg":"0","content":""} -->
								[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text='Entertainment'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg='gray'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg='0'  link_pr_lg='0'  link_pb_lg='0'  link_pl_lg='0'  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='2'  ml_lg='0'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
								<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

								<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"Carsharing","link_bg":"gray","link_pt_lg":"0","link_pr_lg":"0","link_pb_lg":"0","link_pl_lg":"0","font_weight":"font-weight-normal","mb_lg":"2","ml_lg":"0","pl_lg":"0","content":""} -->
								[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text='Carsharing'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg='gray'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg='0'  link_pr_lg='0'  link_pb_lg='0'  link_pl_lg='0'  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='2'  ml_lg='0'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
								<!-- /wp:blockstrap/blockstrap-widget-nav-item --></ul></div>[/bs_nav]
						<!-- /wp:blockstrap/blockstrap-widget-nav --></div>[/bs_container]
					<!-- /wp:blockstrap/blockstrap-widget-container -->

					<!-- wp:blockstrap/blockstrap-widget-container {"container":"","text_color":"white","content":"","className":"block-1618467995"} -->
					[bs_container container=''  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 text-white"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"About","html_tag":"h4","text_color":"light","font_size":"fs-base","mb_lg":""} -->
						<h4 class="wp-block-blockstrap-blockstrap-widget-heading text-light fs-base">About</h4>
						<!-- /wp:blockstrap/blockstrap-widget-heading -->

						<!-- wp:blockstrap/blockstrap-widget-nav {"inside_navbar":"0","container":"nav-light","flex_direction":"flex-column","font_size":"fs-sm","mr_lg":"","ml_lg":"","pl_lg":"0"} -->
						[bs_nav anchor=''  inside_navbar='0'  container='nav-light'  flex_direction='flex-column'  nav_style=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  nav_fill=''  font_size='fs-sm'  font_size_custom=''  bg=''  mt=''  mr='auto'  mb=''  ml='auto'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  width=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-nav" id="navbarNav_"><ul class="wp-block-blockstrap-blockstrap-widget-nav nav me-auto ms-auto ps-0 nav-light flex-column fs-sm"><!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"My account","link_bg":"gray","link_pt_lg":"0","link_pr_lg":"0","link_pb_lg":"0","link_pl_lg":"0","font_weight":"font-weight-normal","mb_lg":"2","ml_lg":"0","pl_lg":"0","content":""} -->
								[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text='My account'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg='gray'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg='0'  link_pr_lg='0'  link_pb_lg='0'  link_pl_lg='0'  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='2'  ml_lg='0'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
								<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

								<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"Wishlist","link_bg":"gray","link_pt_lg":"0","link_pr_lg":"0","link_pb_lg":"0","link_pl_lg":"0","font_weight":"font-weight-normal","mb_lg":"2","ml_lg":"0","pl_lg":"0","content":""} -->
								[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text='Wishlist'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg='gray'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg='0'  link_pr_lg='0'  link_pb_lg='0'  link_pl_lg='0'  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='2'  ml_lg='0'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
								<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

								<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"My listings","link_bg":"gray","link_pt_lg":"0","link_pr_lg":"0","link_pb_lg":"0","link_pl_lg":"0","font_weight":"font-weight-normal","mb_lg":"2","ml_lg":"0","pl_lg":"0","content":""} -->
								[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text='My listings'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg='gray'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg='0'  link_pr_lg='0'  link_pb_lg='0'  link_pl_lg='0'  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='2'  ml_lg='0'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
								<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

								<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"Add listing","link_bg":"gray","link_pt_lg":"0","link_pr_lg":"0","link_pb_lg":"0","link_pl_lg":"0","font_weight":"font-weight-normal","mb_lg":"2","ml_lg":"0","pl_lg":"0","content":""} -->
								[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text='Add listing'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg='gray'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg='0'  link_pr_lg='0'  link_pb_lg='0'  link_pl_lg='0'  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='2'  ml_lg='0'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
								<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

								<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"News","link_bg":"gray","link_pt_lg":"0","link_pr_lg":"0","link_pb_lg":"0","link_pl_lg":"0","font_weight":"font-weight-normal","mb_lg":"2","ml_lg":"0","pl_lg":"0","content":""} -->
								[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text='News'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg='gray'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg='0'  link_pr_lg='0'  link_pb_lg='0'  link_pl_lg='0'  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='2'  ml_lg='0'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
								<!-- /wp:blockstrap/blockstrap-widget-nav-item --></ul></div>[/bs_nav]
						<!-- /wp:blockstrap/blockstrap-widget-nav --></div>[/bs_container]
					<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
				<!-- /wp:blockstrap/blockstrap-widget-container -->

				<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_md":"12","col_lg":"5","ml":"0","ml_lg":"8","pl":"0","content":"","className":"block-1618467995"} -->
				[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md='12'  col_lg='5'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml='0'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg='8'  pt=''  pr=''  pb=''  pl='0'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined ms-0 mb-3 ms-lg-8 ps-0 col-12 col-md-12 col-lg-5 col"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"Recent Posts","html_tag":"h4","text_color":"light","font_size":"fs-base","mb_lg":""} -->
					<h4 class="wp-block-blockstrap-blockstrap-widget-heading text-light fs-base">Recent Posts</h4>
					<!-- /wp:blockstrap/blockstrap-widget-heading -->

					<!-- wp:query {"queryId":0,"query":{"perPage":"2","pages":"1","offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false}} -->
					<div class="wp-block-query"><!-- wp:post-template {"layout":{"type":"default","columnCount":2}} -->
						<!-- wp:blockstrap/blockstrap-widget-container {"container":"row","row_cols_lg":"2","mb_lg":"","display_lg":"d-lg-flex"} -->
						[bs_container container='row'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg='2'  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg='d-lg-flex'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined row-cols-2 d-flex row"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col_lg":"3","mb_lg":""} -->
							[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg='3'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined col-3 col"><!-- wp:blockstrap/blockstrap-widget-image {"img_src":"featured","img_size":"thumbnail","fallback_img_src":"default","img_lazyload":"lazy","img_link_to":"post","img_aspect":"1by1","img_rounded":"rounded","content":""} -->
								[bs_image img_src='featured'  img_image=''  img_image_id=''  img_size='thumbnail'  img_url=''  fallback_img_src='default'  fallback_img_image=''  fallback_img_image_id=''  img_alt=''  img_lazyload='lazy'  img_link_to='post'  img_link=''  img_link_lightbox=''  lightbox_size='full'  img_link_hover_effect=''  text=''  col=''  col_md=''  col_lg=''  img_aspect='1by1'  img_cover=''  img_border=''  img_rounded='rounded'  img_rounded_size=''  img_shadow=''  img_overlay=''  text_color=''  font_size=''  font_size_custom=''  font_weight=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  bg_on_text='false'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  float=''  float_md=''  float_lg=''  img_mask=''  img_mask_position='center center'  visibility_conditions=''  css_class='' ]
								<!-- /wp:blockstrap/blockstrap-widget-image --></div>[/bs_container]
							<!-- /wp:blockstrap/blockstrap-widget-container -->

							<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col_lg":"9","mb_lg":""} -->
							[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg='9'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined col-9 col"><!-- wp:blockstrap/blockstrap-widget-post-title {"html_tag":"h5","is_link":true,"text_color":"light","text_color_custom":"#ea0606","font_size":"0","font_weight":"font-weight-bold","mb_lg":"2","pb_lg":"1","css_class":"nav-link"} -->
								[bs_post_title html_tag='h5'  is_link='true'  stretched_link='false'  text_color='light'  text_color_custom='#ea0606'  font_size='0'  font_size_custom=''  font_line_height=''  font_weight='font-weight-bold'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_on_text='false'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='2'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg='1'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  css_class='nav-link' ]
								<!-- /wp:blockstrap/blockstrap-widget-post-title -->

								<!-- wp:blockstrap/blockstrap-widget-post-excerpt {"html_tag":"div","trim_count":17,"text_color":"white","font_size":"fs-sm","mb_lg":"2","pb_lg":"1","opacity":"opacity-70","content":""} -->
								[bs_post_excerpt html_tag='div'  trim_type='words'  trim_count='17'  trim_append=''  text_color='white'  text_color_custom=''  font_size='fs-sm'  font_size_custom=''  font_line_height=''  font_weight=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_on_text='false'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='2'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg='1'  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  opacity='opacity-70'  css_class='' ]
								<!-- /wp:blockstrap/blockstrap-widget-post-excerpt -->

								<!-- wp:blockstrap/blockstrap-widget-post-info {"type":"date_published","date_format":"custom","date_custom":"M j","is_link":true,"text_color":"light","font_size":"fs-xs","font_weight":"font-weight-normal","mr_lg":"3","content":""} -->
								[bs_post_info type='date_published'  taxonomy='category'  taxonomy_limit=''  date_format='custom'  date_custom='M j'  is_link='true'  custom_url=''  icon_type=''  icon_class=''  before=''  after=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='light'  font_size='fs-xs'  font_size_custom=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg='3'  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  position=''  absolute_position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  zindex=''  visibility_conditions=''  css_class='' ]
								<!-- /wp:blockstrap/blockstrap-widget-post-info -->

								<!-- wp:blockstrap/blockstrap-widget-post-info {"type":"comments","date_format":"custom","date_custom":"M j","is_link":true,"text_color":"light","font_size":"fs-xs","font_weight":"font-weight-normal","mr_lg":"3","content":""} -->
								[bs_post_info type='comments'  taxonomy='category'  taxonomy_limit=''  date_format='custom'  date_custom='M j'  is_link='true'  custom_url=''  icon_type=''  icon_class=''  before=''  after=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='light'  font_size='fs-xs'  font_size_custom=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg='3'  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  position=''  absolute_position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  zindex=''  visibility_conditions=''  css_class='' ]
								<!-- /wp:blockstrap/blockstrap-widget-post-info --></div>[/bs_container]
							<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
						<!-- /wp:blockstrap/blockstrap-widget-container -->
						<!-- /wp:post-template -->

						<!-- wp:query-no-results -->
						<!-- wp:paragraph {"placeholder":"Add text or blocks that will display when a query returns no results."} -->
						<p></p>
						<!-- /wp:paragraph -->
						<!-- /wp:query-no-results --></div>
					<!-- /wp:query --></div>[/bs_container]
				<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
			<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
		<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
	<!-- /wp:blockstrap/blockstrap-widget-container -->

	<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg":"custom-color","bg_color":"#1f1b2d","mb_lg":"0","pb_lg":"0","border":"light","border_type":"border-top","border_opacity":"border-opacity-10","position":"position-relative","anchor":"footer-copyright","className":"block-1618467995"} -->
	[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='custom-color'  bg_color='#1f1b2d'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='0'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg='0'  pl_lg=''  border='light'  border_type='border-top'  border_width=''  border_opacity='border-opacity-10'  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor='footer-copyright'  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-0 pb-0  border-light bg-custom-color container-fluid position-relative border-opacity-10 border-top" style="background-color:#1f1b2d" id="footer-copyright"><!-- wp:blockstrap/blockstrap-widget-container {"mb_lg":"","pt_lg":"2","className":"block-1618467995"} -->
		[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='2'  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-2 container"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","mb_lg":"","pt_lg":"3","pb_lg":"2","flex_align_items_lg":"align-items-lg-center","className":"border-top border-gray-dark"} -->
			[bs_container container='row'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='3'  pr_lg=''  pb_lg='2'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg='align-items-lg-center'  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-3 pb-2 row align-items-center"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_lg":"5","text_align":"text-center","text_align_lg":"text-lg-start","mb":"4","pb":"1","flex_order":"order-5","flex_order_lg":"order-lg-0","className":"block-1618467995"} -->
				[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md=''  col_lg='5'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align='text-center'  text_align_md=''  text_align_lg='text-lg-start'  mt=''  mr=''  mb='4'  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb='1'  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order='order-5'  flex_order_md=''  flex_order_lg='order-lg-0'  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-4 mb-lg-3 pb-1 col-12 col-lg-5 text-center text-lg-start col order-5 order-lg-0"><!-- wp:paragraph {"style":{"color":{"text":"#ccd2d9b8"},"typography":{"fontSize":"0.875rem"}},"className":"mb-0"} -->
					<p class="mb-0 has-text-color" style="color:#ccd2d9b8;font-size:0.875rem">Copyright © 2024 | Powered by <a href="https://wpblockstrap.com/" data-type="URL" data-id="https://wpblockstrap.com/" target="_blank" rel="noreferrer noopener">BlockStrap </a>and <a href="https://wpgeodirectory.com/" data-type="URL" data-id="https://wpgeodirectory.com/" target="_blank" rel="noreferrer noopener">GeoDirectory</a></p>
					<!-- /wp:paragraph --></div>[/bs_container]
				<!-- /wp:blockstrap/blockstrap-widget-container -->

				<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_lg":"7","text_color":"white","text_align":"text-center","ml_lg":"auto","display":"d-block","display_lg":"d-lg-flex","flex_align_items":"align-items-center","flex_justify_content_lg":"justify-content-lg-end","content":"","className":"block-1618467995"} -->
				[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md=''  col_lg='7'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color='white'  text_justify='false'  text_align='text-center'  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg='auto'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display='d-block'  display_md=''  display_lg='d-lg-flex'  flex_align_items='align-items-center'  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg='justify-content-lg-end'  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 ms-auto col-12 col-lg-7 text-white text-center d-block d-lg-flex col align-items-center justify-content-end"><!-- wp:blockstrap/blockstrap-widget-nav {"inside_navbar":"0","container":"nav-light","flex_justify_content":"justify-content-center","font_size":"fs-sm","mr":"","mb":"2","ml":"","mr_lg":"","pl_lg":"0"} -->
					[bs_nav anchor=''  inside_navbar='0'  container='nav-light'  flex_direction=''  nav_style=''  flex_justify_content='justify-content-center'  flex_justify_content_md=''  flex_justify_content_lg=''  nav_fill=''  font_size='fs-sm'  font_size_custom=''  bg=''  mt=''  mr=''  mb='2'  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg='auto'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  width=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-nav" id="navbarNav_"><ul class="wp-block-blockstrap-blockstrap-widget-nav nav mb-2 ms-auto ps-0 nav-light fs-sm justify-content-center"><!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"About","link_bg":"gray","font_weight":"font-weight-normal","content":""} -->
							[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text='About'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg='gray'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
							<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

							<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"Blog","link_bg":"gray","font_weight":"font-weight-normal","content":""} -->
							[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text='Blog'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg='gray'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
							<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

							<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"Support","link_bg":"gray","font_weight":"font-weight-normal","content":""} -->
							[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text='Support'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg='gray'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
							<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

							<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"Contacts","link_bg":"gray","font_weight":"font-weight-normal","mr_md":"auto","content":""} -->
							[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text='Contacts'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg='gray'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md='auto'  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
							<!-- /wp:blockstrap/blockstrap-widget-nav-item --></ul></div>[/bs_nav]
					<!-- /wp:blockstrap/blockstrap-widget-nav -->

					<!-- wp:blockstrap/blockstrap-widget-nav {"inside_navbar":"0","container":"nav-light","flex_justify_content":"justify-content-center","font_size":"fs-sm","mb":"2","mr_lg":"","ml_lg":"","pl_lg":"0"} -->
					[bs_nav anchor=''  inside_navbar='0'  container='nav-light'  flex_direction=''  nav_style=''  flex_justify_content='justify-content-center'  flex_justify_content_md=''  flex_justify_content_lg=''  nav_fill=''  font_size='fs-sm'  font_size_custom=''  bg=''  mt=''  mr='auto'  mb='2'  ml='auto'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  width=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-nav" id="navbarNav_"><ul class="wp-block-blockstrap-blockstrap-widget-nav nav me-auto mb-2 ms-auto ps-0 nav-light fs-sm justify-content-center"><!-- wp:blockstrap/blockstrap-widget-nav-item {"icon_class":"fab fa-facebook-f","link_type":"btn-icon","link_size":"extra-small","link_bg":"translucent-light","font_weight":"font-weight-normal","ml":"0","ml_lg":"auto","content":""} -->
							[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text=''  icon_class='fab fa-facebook-f'  icon_aria_label=''  link_type='btn-icon'  link_size='extra-small'  link_bg='translucent-light'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml='0'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg='auto'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
							<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

							<!-- wp:blockstrap/blockstrap-widget-nav-item {"icon_class":"fab fa-twitter","link_type":"btn-icon","link_size":"extra-small","link_bg":"translucent-light","font_weight":"font-weight-normal","ml_lg":"2","content":""} -->
							[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text=''  icon_class='fab fa-twitter'  icon_aria_label=''  link_type='btn-icon'  link_size='extra-small'  link_bg='translucent-light'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg='2'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
							<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

							<!-- wp:blockstrap/blockstrap-widget-nav-item {"icon_class":"fas fa-paper-plane","link_type":"btn-icon","link_size":"extra-small","link_bg":"translucent-light","font_weight":"font-weight-normal","ml_lg":"2","content":""} -->
							[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text=''  icon_class='fas fa-paper-plane'  icon_aria_label=''  link_type='btn-icon'  link_size='extra-small'  link_bg='translucent-light'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg='2'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
							<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

							<!-- wp:blockstrap/blockstrap-widget-nav-item {"icon_class":"fab fa-facebook-messenger","link_type":"btn-icon","link_size":"extra-small","link_bg":"translucent-light","font_weight":"font-weight-normal","ml_lg":"2","content":""} -->
							[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text=''  icon_class='fab fa-facebook-messenger'  icon_aria_label=''  link_type='btn-icon'  link_size='extra-small'  link_bg='translucent-light'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg='2'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
							<!-- /wp:blockstrap/blockstrap-widget-nav-item --></ul></div>[/bs_nav]
					<!-- /wp:blockstrap/blockstrap-widget-nav --></div>[/bs_container]
				<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
			<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
		<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
	<!-- /wp:blockstrap/blockstrap-widget-container -->
	<?php

	return ob_get_clean();
}
add_filter( 'blockstrap_pattern_footer_default', 'directory_theme_pattern_footer_default', 15 );
