<?php
// THIS FILE IS AUTOGENERATED, PLEASE DON'T EDIT IT DIRECTLY

return array(
	"Clear all" => array(
		__( "Clear all", 'yith-booking-for-woocommerce' ),
	),
	"No items found." => array(
		__( "No items found.", 'yith-booking-for-woocommerce' ),
	),
	"No results for %s" => array(
		__( "No results for %s", 'yith-booking-for-woocommerce' ),
	),
	"Search for items" => array(
		__( "Search for items", 'yith-booking-for-woocommerce' ),
	),
	"%d item selected" => array(
		_n( "%d item selected", "%d items selected", 1, 'yith-booking-for-woocommerce' ),
		_n( "%d item selected", "%d items selected", 2, 'yith-booking-for-woocommerce' ),
	),
	"Loading..." => array(
		__( "Loading...", 'yith-booking-for-woocommerce' ),
	),
	"No products found." => array(
		__( "No products found.", 'yith-booking-for-woocommerce' ),
	),
	"Search products..." => array(
		__( "Search products...", 'yith-booking-for-woocommerce' ),
	),
	"%d product selected" => array(
		_n( "%d product selected", "%d products selected", 1, 'yith-booking-for-woocommerce' ),
		_n( "%d product selected", "%d products selected", 2, 'yith-booking-for-woocommerce' ),
	),
	"No categories found." => array(
		__( "No categories found.", 'yith-booking-for-woocommerce' ),
	),
	"Search categories..." => array(
		__( "Search categories...", 'yith-booking-for-woocommerce' ),
	),
	"%d category selected" => array(
		_n( "%d category selected", "%d categories selected", 1, 'yith-booking-for-woocommerce' ),
		_n( "%d category selected", "%d categories selected", 2, 'yith-booking-for-woocommerce' ),
	),
	"Block nameBookable Products" => array(
		_x( "Bookable Products", "Block name", 'yith-booking-for-woocommerce' ),
	),
	"Bookable Products blockType" => array(
		_x( "Type", "Bookable Products block", 'yith-booking-for-woocommerce' ),
	),
	"Bookable Products blockColumns" => array(
		_x( "Columns", "Bookable Products block", 'yith-booking-for-woocommerce' ),
	),
	"Bookable Products blockRows" => array(
		_x( "Rows", "Bookable Products block", 'yith-booking-for-woocommerce' ),
	),
	"Bookable Products block typesNewest" => array(
		_x( "Newest", "Bookable Products block types", 'yith-booking-for-woocommerce' ),
	),
	"Bookable Products block typesHand-picked products" => array(
		_x( "Hand-picked products", "Bookable Products block types", 'yith-booking-for-woocommerce' ),
	),
	"Bookable Products block typesProduct categories" => array(
		_x( "Product categories", "Bookable Products block types", 'yith-booking-for-woocommerce' ),
	),
	"Bookable Products block typesTop rated" => array(
		_x( "Top rated", "Bookable Products block types", 'yith-booking-for-woocommerce' ),
	),
	"Bookable Products block panel titleProducts" => array(
		_x( "Products", "Bookable Products block panel title", 'yith-booking-for-woocommerce' ),
	),
	"Bookable Products block panel titleCategories" => array(
		_x( "Categories", "Bookable Products block panel title", 'yith-booking-for-woocommerce' ),
	),
	"Bookable Products block panel titleLayout" => array(
		_x( "Layout", "Bookable Products block panel title", 'yith-booking-for-woocommerce' ),
	),
);